services:
  minecraft:
    image: itzg/minecraft-server:java21
    container_name: minecraft
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.21.1"
      MEMORY: "6G"
      ONLINE_MODE: "TRUE"
      MOTD: "Servidor Minecraft Fabric via Docker + Playit"
      OPS: "pkziinn10"
    volumes:
      - ./data:/data
      - ./mods:/data/mods
      - ./config:/data/config
